Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/EndOfLine:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20